version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      # Set your database environment variables here
      DATABASE_URL: postgres://iuser:image9999@database:5432/imagedb
    depends_on:
      - database
    volumes:
      - ./server/images:/app/images   # Map a volume for storing images

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: iuser
      POSTGRES_PASSWORD: image9999
      POSTGRES_DB: imagedb
    ports:
      - '5432:5432'

  db_init:
    image: postgres:13
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: iuser
      POSTGRES_PASSWORD: image9999
      POSTGRES_DB: imagedb
    depends_on:
      - database

volumes:
  pg_data:
